title: "keep going"          
tagline: "one step at a time"
author: "Lily"                      

baseurl: ""
url: ""

permalink: /moment/:title/
timezone: Asia/Tokyo

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
