---
layout: moment           
title: "contemplation hour"   
date: 2026-08-09         
---

Are you sleepy? I am still awake and it is almost 2 am. I have been staying late lately, perhaps because it is summer, perhaps because of my heartbreak residue, perhaps because I am restless, I don't know honestly.<br>
<br>
I have been thinking about my career trajectory. Perhaps because I was conditioned to see how hard my parents worked as entrepreneurs when I was little, I always have a soft spot for startup companies. I really can't picture myself working in a big company. I still can picture myself working in a research institution though, but I feel like it is just not practical enough that the solutions they offer won't translate to real world. Sayang, what if I choose the wrong trajectory? I wish I could talk to you directly now.<br>
<br>
I met this CEO when I was at a startup exhibition last week. The company is really attractive for me, it is an additive manufacturing company. The CEO even messaged me privately through LinkedIn after I sent a connect invitation. I really want to try applying for the R&D internship there. They also have a factory tour this month. I really think I could learn a lot from the company, they are very new, just a year ago. And you know how much I appreciate growth. I want to see the company prosper, and perhaps I can also prosper with the company. I don't know, but I have a good intuition. You know I follow my intuition more than rational decision haha. Well, of course, for now, you don't know that. I don't even know if you exist haha. But, sayang, do you think I should take the risks again and jump off the cliff? This time fortunately I still have my safety net. I applied for the JSPS fellowship, I hope it goes through, but I don't know, everything seems blurry and foggy.<br>
<br>
Sayang, I have been talking to Allah, but I keep having this strange empty feelings in my heart lately. I think I also have a crush with a stranger. I hate this phase. I mean, I don't even know the person and I really don't want to create figures in my head about the person. I did have a conversation with him about a Japanese class, he was very helpful though. He helped Zahrah and I to navigate career options back then as well. Sayang, I think I need to do istikhara about the career decision again. Perhaps, I also should ask my parents about it when I come home next month. I am not sure if they will approve me working in a startup though. However, if the salary is good, the position is R&D, the job is fun, the company is making profit, I think I will jump off the cliff. I have a good feeling about it for now.<br>
<br>
Sayang, I really miss you. I am still walking towards you, but I hope I am more patient than Allah's plans. I do not want to dictate Him. I hope He gives you patience as well. Love you, sayang. Sleep well XOXO.